general:
    control_item: fishing_rod
    update_period: 1

range:
    max_travel_distance: 125.0
    max_search_distance: 75.0
    attack_range: 50.0
    mount_range: 3.0
    goal_range: 3.0

noise_suffix:
    attack_confirmed: '!'
    attack_confused: '?'
    follow_confirmed: '!'
    follow_confused: '?'
    go_confirmed: ''
    go_confused: '?'
    stop_confirmed: ''
    fed_confirmed: ' :D'
    fed_confused: '?'

food:
    - brown_mushroom
    - cactus
    - cake
    - egg
    - ice
    - ink_sack
    - leather
    - long_grass
    - melon
    - red_mushroom
    - red_rose
    - yellow_flower
    - sapling
    - seeds
    - slime_ball
    - wheat
    - sugar
    - sugar_cane

mobs:
    Bat:
        speed: 0.2
        noise: 'Squeeek'
        chance: 100.0
        cost: 0.0
    Blaze:
        speed: 0.4
        noise: 'Kaboom'
        chance: 100.0
        cost: 0.0
    CaveSpider:
        speed: 0.4
        noise: 'Cheeuuuk'
        chance: 100.0
        cost: 0.0
    Chicken:
        speed: 0.2
        noise: 'Cluck'
        chance: 100.0
        cost: 0.0
    Cow:
        speed: 0.3
        noise: 'Mooooo'
        chance: 100.0
        cost: 0.0
    Creeper:
        speed: 0.5F
        noise: 'Hisssss'
        chance: 100.0
        cost: 0.0
    EnderDragon:
        speed: 0.7F
        noise: 'Rawwwwwwr'
        chance: 100.0
        cost: 0.0
    Enderman:
        speed: 0.2
        noise: 'Mooooaaan'
        chance: 100.0
        cost: 0.0
    Ghast:
        speed: 0.5
        noise: 'Hooooo'
        chance: 100.0
        cost: 0.0
    Giant:
        speed: 0.5
        noise: 'MOOOOAAAN'
        chance: 100.0
        cost: 0.0
    LavaSlime:
        speed: 0.2
        noise: 'Glub'
        chance: 100.0
        cost: 0.0
    Monster:
        speed: 0.4
        noise: 'Rawr'
        chance: 100.0
        cost: 0.0
    MushroomCow:
        speed: 0.3
        noise: 'Moo00sh'
        chance: 100.0
        cost: 0.0
    Ozelot:
        speed: 0.6
        noise: 'Meow'
        chance: 100.0
        cost: 0.0
    Pig:
        speed: 0.25
        noise: 'Oink'
        chance: 100.0
        cost: 0.0
    PigZombie:
        speed: 0.4
        noise: 'Mooooiiink'
        chance: 100.0
        cost: 0.0
    Sheep:
        speed: 0.25
        noise: 'Baaaaa'
        chance: 100.0
        cost: 0.0
    Silverfish:
        speed: 0.2
        noise: 'Cheeuuuk'
        chance: 100.0
        cost: 0.0
    Skeleton:
        speed: 0.2
        noise: '*silence*'
        chance: 100.0
        cost: 0.0
    Slime:
        speed: 0.2
        noise: 'Blluuurrrp'
        chance: 100.0
        cost: 0.0
    SnowMan:
        speed: 0.3
        noise: '*silence*'
        chance: 100.0
        cost: 0.0
    Spider:
        speed: 0.4
        noise: 'Cheeuuuk'
        chance: 100.0
        cost: 0.0
    Squid:
        speed: 0.6
        noise: 'Glub'
        chance: 100.0
        cost: 0.0
    Villager:
        speed: 0.3
        noise: 'Mhmm'
        chance: 100.0
        cost: 0.0
    VillagerGolem:
        speed: 0.2
        noise: 'Grrr'
        chance: 100.0
        cost: 0.0
    Witch:
        speed: 0.3
        noise: 'Ha ha, ha, ha, haaaa!'
        chance: 100.0
        cost: 0.0
    WitherBoss:
        speed: 0.7F
        noise: '*silence*'
        chance: 100.0
        cost: 0.0
    WitherSkull:
        speed: 0.2
        noise: '*silence*'
        chance: 100.0
        cost: 0.0
    Wolf:
        speed: 0.6
        noise: 'Woof'
        chance: 100.0
        cost: 0.0
    Zombie:
        speed: 0.2
        noise: 'Mooooaaan'
        chance: 100.0
        cost: 0.0