name: MobRider
main: com.edwardhand.mobrider.MobRider
version: 0.4dev-b3
depend: [Vault]
commands:
  mob:
    description: MobRider commands
    usage: |
           Usage:
           /<command> go <direction> - go n, north, northeast, etc.
           /<command> goto <player|mob> - go to nearby player or mob
           /<command> goto <x> <z> - go to specific x, z coordinates
           /<command> follow <player|mob> - follow nearby player or mob
           /<command> stop - stop
           /<command> attack <player|mob> - attack nearby player or mob
permissions:
    mobRider.command.*:
        description: Player can use all /mob commands
        children:
            mobRider.command.goto: true
            mobRider.command.attack: true
            mobRider.command.go: true
            mobRider.command.stop: true
            mobRider.command.follow: true
    mobRider.command.goto:
        description: Player can use /mob goto
        default: op
    mobRider.command.attack:
        description: Player can use /mob attack
        default: op
    mobRider.command.go:
        description: Player can use /mob go
        default: op
    mobRider.command.stop:
        description: Player can use /mob stop
        default: op
    mobRider.command.follow:
        description: Player can use /mob follow
        default: op
    mobRider.players:
        description: Player can mount other players
        default: op
    mobRider.animals:
        description: Player can mount animals
        default: op
    mobRider.monsters:
        description: Player can mount monster
        default: op
